### ISSUE TITLE
Depth data

### ISSUE THREAD

**Issue by pranali3215** [r9y9/pylibfreenect2#27]
Hi ! I have been going through the code and trying to understand it.
Is there a function that returns the depth given a ROI ?

**Comment by r9y9** [comment]
No, but you can slice a numpy array if you convert depth frame to array.

http://r9y9.github.io/pylibfreenect2/api.html#pylibfreenect2.libfreenect2.Frame.asarray

**Comment by pranali3215** [comment]
Thanks !

**Comment by pranali3215** [comment]
Hey !! I did as suggested but I am getting values that do not seem to be accurate. The current values I'm getting are in double digit, for example 30 mm. I used to use this code with Kinect 1 and now I have shifted to Kinect 2. Is there any difference in the way the depth data is coming as compared to Kinect 1 ?
