### ISSUE TITLE
How can I get the LD_LIBRARY_PATH path

### ISSUE THREAD

**Issue by wuguangbin1230** [r9y9/pylibfreenect2#42]
## **## I install the pylibfreenect2 by the command ( wgb@wgb:~/wgb_install/pylibfreenect2-master$ python setup.py install) and got the following Instructions**. Did ｔｈｅm suggest that I installed correct?
/home/wgb/anaconda2/lib/python2.7/site-packages/setuptools/dist.py:341: UserWarning: Normalizing '0.1.3-dev' to '0.1.3.dev0'
  normalized_version,
running install
running bdist_egg
running egg_info
writing requirements to pylibfreenect2.egg-info/requires.txt
writing pylibfreenect2.egg-info/PKG-INFO
writing top-level names to pylibfreenect2.egg-info/top_level.txt
writing dependency_links to pylibfreenect2.egg-info/dependency_links.txt
reading manifest file 'pylibfreenect2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pylibfreenect2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-2.7/tests/test_libfreenect2.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-2.7/tests/__init__.py -> build/bdist.linux-x86_64/egg/tests
creating build/bdist.linux-x86_64/egg/pylibfreenect2
copying build/lib.linux-x86_64-2.7/pylibfreenect2/libfreenect2.so -> build/bdist.linux-x86_64/egg/pylibfreenect2
copying build/lib.linux-x86_64-2.7/pylibfreenect2/__init__.py -> build/bdist.linux-x86_64/egg/pylibfreenect2
byte-compiling build/bdist.linux-x86_64/egg/tests/test_libfreenect2.py to test_libfreenect2.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pylibfreenect2/__init__.py to __init__.pyc
creating stub loader for pylibfreenect2/libfreenect2.so
byte-compiling build/bdist.linux-x86_64/egg/pylibfreenect2/libfreenect2.py to libfreenect2.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pylibfreenect2.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pylibfreenect2.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pylibfreenect2.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pylibfreenect2.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pylibfreenect2.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist/pylibfreenect2-0.1.3.dev0-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pylibfreenect2-0.1.3.dev0-py2.7-linux-x86_64.egg
Removing /home/wgb/anaconda2/lib/python2.7/site-packages/pylibfreenect2-0.1.3.dev0-py2.7-linux-x86_64.egg
Copying pylibfreenect2-0.1.3.dev0-py2.7-linux-x86_64.egg to /home/wgb/anaconda2/lib/python2.7/site-packages
pylibfreenect2 0.1.3.dev0 is already the active version in easy-install.pth

Installed /home/wgb/anaconda2/lib/python2.7/site-packages/pylibfreenect2-0.1.3.dev0-py2.7-linux-x86_64.egg
Processing dependencies for pylibfreenect2==0.1.3.dev0
Searching for enum34==1.1.6
Best match: enum34 1.1.6
Adding enum34 1.1.6 to easy-install.pth file

Using /home/wgb/anaconda2/lib/python2.7/site-packages
Searching for numpy==1.13.1
Best match: numpy 1.13.1
Adding numpy 1.13.1 to easy-install.pth file

Using /home/wgb/anaconda2/lib/python2.7/site-packages
Finished processing dependencies for pylibfreenect2==0.1.3.dev0

**Comment by r9y9** [comment]
If you get no errors at installation time,  yes, you should be ready to use pylibfreenect2. Please don't create a new issue if your interest is #41.
