### ISSUE TITLE
Timeout on listener.waitForNewFrame()

### ISSUE THREAD

**Issue by ptmcgrat** [r9y9/pylibfreenect2#46]
Is it possible to use timeout argument of the c++ code in the python bindings for waitForNewFrame?

**Comment by r9y9** [comment]
Sorry for the delay, Yes, it's definitely possible. Steps to implement:

- Add a function signature to the next line of https://github.com/r9y9/pylibfreenect2/blob/7fc73dedd7b18109630cbfb10a53f514c443f839/pylibfreenect2/libfreenect2/libfreenect2.pxd#L41
- Add cython wrapper similar to https://github.com/r9y9/pylibfreenect2/blob/7fc73dedd7b18109630cbfb10a53f514c443f839/pylibfreenect2/libfreenect2.pyx#L553

I don't have kinect right now, so I would be appreciated if you or someone could make a PR for this.
