### ISSUE TITLE
Find RGB coordinates in the depth map

### ISSUE THREAD

**Issue by AAcquier** [r9y9/pylibfreenect2#56]
Hello,

I am trying to find a way find the corresponding point from RGB image (1920x1080) on a depth map (512x424), is there any formula or exampleI can find

**Comment by gf0507033** [comment]
[Yup](https://github.com/OpenKinect/libfreenect2/blob/master/src/registration.cpp#L87-L106). See [also](https://github.com/OpenKinect/libfreenect2/issues/41#issuecomment-72022111).
