### ISSUE TITLE
how to read a frame map by frame

### ISSUE THREAD

**Issue by yzf123456** [r9y9/pylibfreenect2#62]
Hello,
I have already installed pylibfreenect2, and can open kinect 2 in Python. I want to read image information frame by frame, but I don't know how to write the code?Someone has relevant source code, I am very grateful.

**Comment by r9y9** [comment]
Please see https://github.com/r9y9/pylibfreenect2/blob/4bea7cb58798dec75585768cf5a8fb4084813cd1/examples/multiframe_listener.py#L61-L92.

**Comment by yzf123456** [comment]
@https://github.com/r9y9，Thank you very much for your answer.
